name : pull-request
on:
  push:
    branches: [Textures, Shapes]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_label: "automerge"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.GITHUB_TOKEN }}
